version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "ecs-shutdown-scheduler"
s3_prefix = "ecs-shutdown-scheduler"
capabilities = "CAPABILITY_IAM"
resolve_s3 = true
region = "eu-west-1"
confirm_changeset = true
parameter_overrides = "Whitelist=\"dev,test,preprod\" StartSchedule=\"cron(0 7 * * ? *)\" ShutdownSchedule=\"cron(0 21 * * ? *)\""
image_repositories = []
