AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  ecs-shutdown-scheduler

  Sample SAM Template for ecs-shutdown-scheduler

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 5

Parameters:
  Whitelist:
    Type: String
    Default: "dev,test,preprod"
  StartSchedule:
    Type: String
    Default: "cron(0 7 * * ? *)"
  ShutdownSchedule:
    Type: String
    Default: "cron(0 21 * * ? *)"


Resources:
  LambdaFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: ecs_shutdown_scheduler/src
      Handler: schedule_containers.lambda_handler
      Runtime: python3.8
      Role: !GetAtt LambdaRole.Arn
      Environment:
        Variables:
          LOG_LEVEL: INFO
          WHITELIST: !Ref Whitelist
      Events:
        Start:
          Type: Schedule
          Properties:
            Schedule: !Ref StartSchedule
            Input: "{\"Task\": \"start\"}"
        Shutdown:
          Type: Schedule
          Properties:
            Schedule: !Ref ShutdownSchedule
            Input: "{\"Task\": \"shutdown\"}"

  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        -
          PolicyName: "Autoscaling"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
               -
                 Sid: "Autoscaling"
                 Effect: "Allow"
                 Action:
                  - "application-autoscaling:DescribeScalableTargets"
                  - "application-autoscaling:RegisterScalableTarget"
                 Resource: "*"
        -
          PolicyName: "ECS"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
               -
                 Sid: "List"
                 Effect: "Allow"
                 Action:
                  - "ecs:ListClusters"
                  - "ecs:ListServices"
                 Resource: "*"
               -
                 Sid: "Services"
                 Effect: "Allow"
                 Action:
                  - "ecs:UpdateService"
                  - "ecs:DescribeServices"
                 Resource: !Sub "arn:aws:ecs:${AWS::Region}:${AWS::AccountId}:service/*"
        -
          PolicyName: "ParameterStore"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
               -
                 Sid: "ParameterStore"
                 Effect: "Allow"
                 Action:
                  - "ssm:GetParameter"
                  - "ssm:PutParameter"
                 Resource: !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/ecs-shutdown-scheduler/*"
